# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WorldBeers' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Glide', '~> 1.0'
  # Pods for WorldBeers

  target 'WorldBeersTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WorldBeersUITests' do
    # Pods for testing
  end

end
